# -*- coding: utf-8 -*-
"""韩国线行程家族（人工归并）：住宿骨架相同或只差 1–2 个节点的线路归一族；一条线路可属多个家族。
standard = 家族内数据最完整、最具代表性的一条。"""

FAMILIES = [
    {"id": "K01", "name_cn": "首尔 + 京畿深度（单城放射，跟团）", "name_en": "Seoul & Gyeonggi Deep-dive (group)",
     "skeleton": [("Seoul", 5)], "standard": "KRSRAS",
     "members": ["KRSRAS", "KRICNW", "KR8IG", "KGYE09", "KGYE08"],
     "note_cn": "首尔住满，每天放射到京畿/仁川/江原近郊（南怡岛、小法国村、晨静树木园、爱宝乐园、水原华城、DMZ、金浦/江华）。KR8IG 与 Dynasty 两条家庭线前段住仁川/金浦（夜航抵达 + 京畿西部景点），EU 冬季 6 天版 KRICNW 为最短价位款。"},
    {"id": "K02", "name_cn": "首尔自由行（酒店 + 一日游自选）", "name_en": "Seoul Free & Easy",
     "skeleton": [("Seoul", 4)], "standard": "KR6FGT",
     "members": ["KR5MXT", "KR5SA", "KR6FNT", "KR6FGT", "CB-8885"],
     "note_cn": "Chan Brothers「Free & Easy+」：机票 + 首尔酒店 + 1–2 个半日/一日游模块（南怡岛、江华 DMZ、首尔市区、主题设计体验 Atelier）。CB-8885 为私人包车日程样本（无住宿）。"},
    {"id": "K03", "name_cn": "济州 + 首尔（双城飞线）", "name_en": "Jeju + Seoul",
     "skeleton": [("Jeju", 2), ("Seoul", 4)], "standard": "KR8TGG",
     "members": ["KR8TGG", "KJJS09", "KR10EG", "KR8PQG"],
     "note_cn": "仁川进 → 金浦飞济州 → 飞回金浦住首尔。KJJS09 济州 5 晚深度版；KR10EG 10 天慢游版在济州后加忠清（瑞山）与全州两站；KR8PQG 济州 3 晚后从江陵陆路回首尔（济州—江原只能飞襄阳/原州或经首尔）。"},
    {"id": "K04", "name_cn": "济州 > 釜山 > 首尔（三城两段内陆航班）", "name_en": "Jeju–Busan–Seoul",
     "skeleton": [("Jeju", 2), ("Busan", 2), ("Seoul", 2)], "standard": "KRJBUS",
     "members": ["KRJBUS", "KRJBTS", "KRKA09", "KRKG09"],
     "note_cn": "仁川进 → 金浦飞济州 → 济州飞釜山 → 釜山回首尔（KTX 或飞金浦）。EU 春季版 KRJBTS 加镇海军港节/樱花；Dynasty 两条为高端小团（9 天 7 晚，含米其林餐）。"},
    {"id": "K05", "name_cn": "大韩全景（济州 > 庆尚 > 全州/江原 > 首尔，陆路北上）", "name_en": "Grand Korea overland",
     "skeleton": [("Jeju", 2), ("Daegu", 1), ("Jeonju", 1), ("Seoul", 2)], "standard": "KR8GKG",
     "members": ["KR8GKG", "KR8GAG", "KR8GEG", "KR8BKG", "KR8SEG"],
     "note_cn": "Chan Brothers 主力 8 天：济州 2 晚后飞釜山/大邱，大巴北上经全州（或平昌滑雪）回首尔，一路覆盖 4–5 个道。KR8GEG 为英文导游版；KR8BKG 春季樱花版；KR8SEG 冬季把全州换成平昌滑雪。"},
    {"id": "K06", "name_cn": "釜山 + 庆州 + 首尔（南北纵贯）", "name_en": "Busan–Gyeongju–Seoul",
     "skeleton": [("Busan", 2), ("Gyeongju", 1), ("Seoul", 3)], "standard": "KRBBUW",
     "members": ["KRBBUW", "KRBBFS", "KR8SNG", "KR8BSG"],
     "note_cn": "釜山进（或仁川进飞釜山）→ 庆州 → 大巴/KTX 北上首尔。EU KRBBFS 为 11 月釜山烟花节专团；KR8SNG 仁川进先飞釜山再经大邱回首尔；KR8BSG 冬季在庆州后插平昌滑雪 1 晚。"},
    {"id": "K07", "name_cn": "江原道（滑雪 / 赏花 / 赏枫）+ 首尔", "name_en": "Gangwon seasonal + Seoul",
     "skeleton": [("Pyeongchang", 2), ("Seoul", 3)], "standard": "KR8RWG",
     "members": ["KR8RWG", "KR8FMG", "KR8SVG", "KR8BG", "KRWSKW", "KR6NST"],
     "note_cn": "首尔 + 江原道度假村 2–3 晚（龙平/阿尔卑西亚/Welli Hilli/Vivaldi），冬季滑雪、春季樱花（KR8BG）、秋季枫叶（KR8FMG）同一骨架换季节内容。EU KRWSKW 先住束草（雪岳山）再上平昌。KR6NST 为自由行版。"},
    {"id": "K08", "name_cn": "全罗道美食慢游（全州 / 木浦 / 光州 / 潭阳）", "name_en": "Jeolla food & slow travel",
     "skeleton": [("Jeonju", 2), ("Seoul", 3)], "standard": "KR8YYG",
     "members": ["KR8YYG", "KRAT09", "KR8UG", "KR10EG"],
     "note_cn": "首尔进出，西南部住全州/木浦做放射（潭阳竹林、顺天湾、宝城茶园、内藏山、曾岛盐田）。KRAT09 为秋季枫叶专线（内藏山、潭阳水杉）；KR8UG 为电台 DJ 带团主题团，加泰安/瑞山海洋疗养。"},
    {"id": "K09", "name_cn": "南部海岸（釜山 + 全罗南道 / 庆尚南道）", "name_en": "Southern coast",
     "skeleton": [("Busan", 2), ("Yeosu", 2), ("Busan", 3)], "standard": "KBJC09",
     "members": ["KBJC09", "KGUB09"],
     "note_cn": "Dynasty 小团：釜山进出，往西到丽水/顺天/光阳（春季梅花、樱花）或南海/河东/蔚山。目前只有高端小团形态，是 WEBUY 货架可补的空白。"},
    {"id": "K10", "name_cn": "釜山自由行（+ 庆州 / 巨济）", "name_en": "Busan Free & Easy",
     "skeleton": [("Busan", 3)], "standard": "KR5BJT",
     "members": ["KR5BJT", "KR5BGT", "CB-8546"],
     "note_cn": "釜山直飞进出，住釜山 3 晚，含庆州或巨济一日游模块。CB-8546 为私人包车日程样本。"},
    {"id": "K11", "name_cn": "济州单岛深度", "name_en": "Jeju Island",
     "skeleton": [("Jeju", 5)], "standard": "KR6JMG",
     "members": ["KR6JMG", "KR6JLT", "KR4JT", "CB-8880"],
     "note_cn": "新加坡直飞济州（或经仁川转机），住满济州，东线（城山、牛岛、涉地可支）/ 西线（雪绿茶、挟才、山房山）/ 南线（中文、西归浦）三条日线轮换。KR6JMG 为跟团版，其余为自由行与包车样本。"},
    {"id": "K12", "name_cn": "韩国环线拼团（首尔出发，地接英文团）", "name_en": "Korea round tour (join-in)",
     "skeleton": [("Jeonju", 1), ("Gwangju", 1), ("Busan", 2), ("Gyeongju", 1), ("Pyeongchang", 1)], "standard": "KTE-RT7",
     "members": ["KTE-RT7", "KTE-W4", "KTE-E4", "KTE-UK16"],
     "note_cn": "首尔地接社 KoreaTravelEasy 的固定班期拼团：西线（公州·全州·白羊寺·宝城·顺天）+ 东线（釜山·庆州·安东·雪岳山），每周固定出发、1 人成团。可作为 WEBUY 自由行客人的「地接拼团模块」，或小团地接报价对标。"},
    {"id": "K13", "name_cn": "忠清道深度（大田 / 扶余 / 公州）", "name_en": "Chungcheong",
     "skeleton": [("Daejeon", 2), ("Buyeo", 2), ("Seoul", 1)], "standard": "KRDB06",
     "members": ["KRDB06", "KR8UG"],
     "note_cn": "百济古都（扶余、公州）+ 大田（圣心堂、世博科学公园、鸡足山黄土路）。新兴主题，只有 Dynasty 小团与 CB 电台团涉及。"},
    {"id": "K14", "name_cn": "东海岸短线（江陵 / 东海 / 郁陵岛）", "name_en": "East coast short trips",
     "skeleton": [("Gangneung", 1)], "standard": "KTE-GW2",
     "members": ["KTE-GW2", "KTE-ULL3", "KR8PQG"],
     "note_cn": "首尔出发 KTX 2 天 1 夜（东海墨湖港、湫岩、正东津、江陵咖啡街）与郁陵岛 3 天（浦项夜船）。可挂在首尔自由行后做加长段。"},
]
