# -*- coding: utf-8 -*-
"""韩国景点词典：正则 → (标准英文名, 中文名, 城市 key, 类别)。
从行程逐日描述 / 每日亮点里抽景点用；中文为整理时的通用译名（非官方）。
类别：palace 宫殿 · temple 寺庙 · heritage 史迹/世界遗产 · nature 自然 · beach 海岸/海滩 · island 海岛 · park 公园/花园/树木园
      museum 博物馆/美术馆 · themepark 主题乐园 · village 传统村落 · district 街区/商圈 · market 传统市场 · outlet 奥特莱斯/商场
      observatory 观景台/塔 · ride 缆车/游船/小火车 · show 演出 · experience 体验 · farm 农场/采摘 · cafe 网红咖啡/拍照点
      ski 滑雪场 · festival 节庆/季节限定 · shopstop 团队购物站（人参/化妆品/护肝/免税）· dmz 安保观光
"""
import re

CAT_CN = {"palace": "宫殿", "temple": "寺庙", "heritage": "史迹/世界遗产", "nature": "自然风景", "beach": "海岸/海滩", "island": "海岛",
          "park": "公园/花园/树木园", "museum": "博物馆/美术馆", "themepark": "主题乐园", "village": "传统村落/韩屋村", "district": "街区/商圈",
          "market": "传统市场", "outlet": "奥特莱斯/商场", "observatory": "观景台/塔", "ride": "缆车/游船/小火车", "show": "演出",
          "experience": "体验", "farm": "农场/采摘", "cafe": "网红咖啡/拍照点", "ski": "滑雪场", "festival": "节庆/季节限定",
          "shopstop": "团队购物站", "dmz": "安保观光（DMZ）"}

G = [
    # ---------- 首尔 ----------
    (r"gyeongbok", "Gyeongbokgung Palace", "景福宫", "seoul", "palace"),
    (r"changdeok|secret garden|huwon", "Changdeokgung Palace", "昌德宫", "seoul", "palace"),
    (r"deoksu", "Deoksugung Palace", "德寿宫", "seoul", "palace"),
    (r"changgyeong", "Changgyeonggung Palace", "昌庆宫", "seoul", "palace"),
    (r"unhyeon", "Unhyeongung Palace", "云岘宫", "seoul", "palace"),
    (r"national folk museum", "National Folk Museum of Korea", "国立民俗博物馆", "seoul", "museum"),
    (r"national museum of korea(?! contemporary)", "National Museum of Korea", "国立中央博物馆", "seoul", "museum"),
    (r"contemporary history", "National Museum of Korean Contemporary History", "大韩民国历史博物馆", "seoul", "museum"),
    (r"gwanghwamun", "Gwanghwamun Square", "光化门广场", "seoul", "district"),
    (r"cheonggyecheon", "Cheonggyecheon Stream", "清溪川", "seoul", "district"),
    (r"(?<!southern )blue house|(?<![\"“])cheong ?wa ?dae", "Cheong Wa Dae (Blue House)", "青瓦台", "seoul", "heritage"),
    (r"bukchon", "Bukchon Hanok Village", "北村韩屋村", "seoul", "village"),
    (r"ikseon", "Ikseon-dong Hanok Street", "益善洞韩屋街", "seoul", "village"),
    (r"insa-?dong|ssamziegil", "Insadong & Ssamziegil", "仁寺洞·森吉街", "seoul", "district"),
    (r"jogyesa", "Jogyesa Temple", "曹溪寺", "seoul", "temple"),
    (r"bongeunsa", "Bongeunsa Temple", "奉恩寺", "seoul", "temple"),
    (r"(?<!chuncheon )myeong-?dong(?! cathedral)", "Myeongdong Shopping Street", "明洞购物街", "seoul", "district"),
    (r"myeongdong cathedral", "Myeongdong Cathedral", "明洞天主教堂", "seoul", "heritage"),
    (r"n seoul tower|namsan(?:\s+seoul)? tower|namsan tower|seoul tower", "N Seoul Tower (Namsan)", "N首尔塔（南山塔）", "seoul", "observatory"),
    (r"seoul sky|lotte world tower", "Lotte World Tower Seoul Sky", "乐天世界塔 Seoul Sky", "seoul", "observatory"),
    (r"lotte world(?! tower)", "Lotte World Adventure", "乐天世界", "seoul", "themepark"),
    (r"seokchon", "Seokchon Lake", "石村湖", "seoul", "park"),
    (r"\bcoex\b|starfield (?:coex )?library(?! suwon)|starfield coex", "COEX Mall & Starfield Library", "COEX 星空图书馆", "seoul", "outlet"),
    (r"dongdaemun design plaza|\bddp\b", "Dongdaemun Design Plaza (DDP)", "东大门设计广场 DDP", "seoul", "district"),
    (r"dongdaemun(?! design)", "Dongdaemun Market", "东大门市场", "seoul", "market"),
    (r"gwangjang", "Gwangjang Market", "广藏市场", "seoul", "market"),
    (r"namdaemun", "Namdaemun Market", "南大门市场", "seoul", "market"),
    (r"tongin", "Tongin Market", "通仁市场", "seoul", "market"),
    (r"mangwon", "Mangwon Market & Mangridan-gil", "望远市场·望理团路", "seoul", "market"),
    (r"hongdae|hongik", "Hongdae (Hongik Univ. Street)", "弘大", "seoul", "district"),
    (r"seongsu", "Seongsu-dong", "圣水洞", "seoul", "district"),
    (r"gangnam", "Gangnam", "江南", "seoul", "district"),
    (r"garosu", "Garosu-gil", "林荫道（新沙洞）", "seoul", "district"),
    (r"itaewon", "Itaewon", "梨泰院", "seoul", "district"),
    (r"yeouido|yeo.ui-?do|yoonjung", "Yeouido Yunjung-ro Cherry Blossom Street", "汝矣岛轮中路樱花街", "seoul", "festival"),
    (r"han river (?:night )?(?:vip )?cruise|hangang cruise|e-?land cruise", "Han River Cruise", "汉江游船", "seoul", "ride"),
    (r"han river park|hangang park|banpo", "Han River Park", "汉江公园", "seoul", "park"),
    (r"seoul forest", "Seoul Forest", "首尔林", "seoul", "park"),
    (r"olympic park", "Olympic Park", "奥林匹克公园", "seoul", "park"),
    (r"culture station seoul|seoul 284", "Culture Station Seoul 284", "文化站首尔284（旧首尔站）", "seoul", "museum"),
    (r"mullae", "Mullae-dong Art Village", "文来洞艺术村", "seoul", "district"),
    (r"nanta", "NANTA Show", "乱打秀", "seoul", "show"),
    (r"painter'?s'? show|painters show", "The Painters Show", "画家秀（The Painters）", "seoul", "show"),
    (r"hero show|jump show", "JUMP / Hero Show", "武术喜剧秀", "seoul", "show"),
    (r"taekwon", "Taekwondo Show", "跆拳道表演", "seoul", "show"),
    (r"war memorial", "War Memorial of Korea", "战争纪念馆", "seoul", "museum"),
    (r"hanbok", "Hanbok Dress-up Experience", "韩服体验", "seoul", "experience"),
    (r"kimchi", "Kimchi-making Experience", "腌泡菜体验", "seoul", "experience"),
    (r"gochujang", "Gochujang-making Experience", "辣椒酱制作体验", "gimpo", "experience"),
    (r"tteokbokki cooking", "Tteokbokki Cooking Class", "炒年糕料理课", "seoul", "experience"),
    (r"jjimjilbang", "Jjimjilbang (Korean Sauna)", "汗蒸幕", "seoul", "experience"),
    (r"spoon mapping", "Spoon Mapping Café", "Spoon Mapping 咖啡", "seoul", "cafe"),
    (r"lotte duty free|duty[- ]free", "Duty-free Shop", "免税店", "seoul", "shopstop"),
    (r"ginseng (?:showroom|shop|gallery|centre|center|experience)|korean ginseng shop|red ginseng", "Ginseng Shop", "高丽人参店", "seoul", "shopstop"),
    (r"healthy liver|liver (?:showroom|gallery)|hovenia", "Healthy Liver Showroom", "护肝宝店", "seoul", "shopstop"),
    (r"cosmetic(?:s)? shop", "Cosmetics Shop", "化妆品店", "seoul", "shopstop"),
    (r"amethyst", "Amethyst Showroom", "紫水晶店", "seoul", "shopstop"),
    (r"haru scalp|scalp care", "Scalp Care Clinic", "头皮护理体验", "seoul", "shopstop"),
    (r"chuna", "Korean Chuna Therapy", "韩式推拿", "seoul", "experience"),
    (r"lotte mart", "Lotte Mart", "乐天超市", "seoul", "shopstop"),
    (r"\bk-?pop\b|hybe|sm town|smtown|\bjyp\b", "K-pop Spots", "K-pop 打卡点", "seoul", "district"),
    (r"\bbts\b", "BTS Spots", "BTS 圣地巡礼", "seoul", "district"),
    # ---------- 京畿 / 仁川 ----------
    (r"nami island|namiseom|namisum", "Nami Island", "南怡岛", "namiisland", "island"),
    (r"petite france", "Petite France", "小法国村", "gapyeong", "village"),
    (r"italian village|pinocchio village", "Gapyeong Italian Village (Pinocchio)", "意大利村（皮诺曹村）", "gapyeong", "village"),
    (r"morning calm", "The Garden of Morning Calm", "晨静树木园", "gapyeong", "park"),
    (r"gapyeong rail ?bike|gangchon rail", "Gangchon Rail Park", "江村铁路自行车", "chuncheon", "ride"),
    (r"gapyeong cruise", "Gapyeong Cruise", "加平游船", "gapyeong", "ride"),
    (r"begonia bird", "Gapyeong Begonia Bird Park", "加平秋海棠鸟园", "gapyeong", "park"),
    (r"daegwallyeong|sky ?ranch", "Daegwallyeong Sky Ranch", "大关岭天空牧场", "pyeongchang", "farm"),
    (r"gapyeong sheep", "Gapyeong Sheep Farm", "加平羊群牧场", "gapyeong", "farm"),
    (r"alpaca", "Alpaca World", "羊驼世界", "hongcheon", "farm"),
    (r"everland", "Everland", "爱宝乐园", "yongin", "themepark"),
    (r"caribbean bay", "Caribbean Bay", "加勒比海湾水上乐园", "yongin", "themepark"),
    (r"korean folk village", "Korean Folk Village", "韩国民俗村", "yongin", "village"),
    (r"hwaseong|heaseong|suwon fortress", "Suwon Hwaseong Fortress", "水原华城", "suwon", "heritage"),
    (r"starfield (?:library )?suwon|suwon starfield|starfield shopping mall", "Starfield Suwon", "水原星空图书馆（Starfield）", "suwon", "outlet"),
    (r"legoland", "Legoland Korea", "乐高乐园", "chuncheon", "themepark"),
    (r"chuncheon myeongdong|dakgalbi", "Chuncheon Myeongdong Dakgalbi Street", "春川明洞辣炒鸡排街", "chuncheon", "district"),
    (r"soyang", "Soyang River Skywalk", "昭阳江天空步道", "chuncheon", "observatory"),
    (r"herb island", "Pocheon Herb Island", "抱川香草岛", "pocheon", "park"),
    (r"pocheon art valley", "Pocheon Art Valley", "抱川艺谷", "pocheon", "park"),
    (r"aegibong", "Aegibong Peace Ecopark", "爱妓峰和平生态公园", "gimpo", "dmz"),
    (r"gimpo (?:hyundai )?premium outlet|hyundai premium outlet gimpo", "Hyundai Premium Outlet Gimpo", "金浦现代名品奥特莱斯", "gimpo", "outlet"),
    (r"rice flower", "Rice Flower's Farmer (Gimpo)", "金浦米花农场", "gimpo", "farm"),
    (r"marina ?bay seoul|ara ?(?:hotel|waterway)|gyeongin ara", "Gyeongin Ara Waterway", "京仁阿拉运河", "gimpo", "park"),
    (r"songdo central park", "Songdo Central Park", "松岛中央公园", "incheon", "park"),
    (r"songdo (?:hyundai )?premium outlet|hyundai premium outlet songdo", "Hyundai Premium Outlet Songdo", "松岛现代名品奥特莱斯", "incheon", "outlet"),
    (r"triple street", "Songdo Triple Street", "松岛 Triple Street", "incheon", "outlet"),
    (r"songdo cloud", "Songdo Cloud Walk", "松岛云端步道", "incheon", "observatory"),
    (r"chinatown|jjajangmyeon|jajangmyeon", "Incheon Chinatown & Jjajangmyeon Museum", "仁川中华街·炸酱面博物馆", "incheon", "district"),
    (r"songwol|fairy ?tale village", "Songwol-dong Fairy Tale Village", "松月洞童话村", "incheon", "village"),
    (r"open port|jemulpo", "Incheon Open Port Street", "仁川开港场街", "incheon", "district"),
    (r"wolmido", "Wolmido", "月尾岛", "incheon", "district"),
    (r"inspire resort", "Inspire Entertainment Resort", "Inspire 度假村", "incheon", "district"),
    (r"paradise city", "Paradise City", "百乐达斯城", "incheon", "district"),
    (r"ganghwa (?:peace )?observatory|ganghwado peace|peace observatory", "Ganghwa Peace Observatory", "江华和平展望台", "ganghwa", "dmz"),
    (r"ganghwa luge", "Ganghwa Seaside Resort Luge", "江华斜坡滑车（Luge）", "ganghwa", "ride"),
    (r"ganghwa (?:anglican )?church|ganghwa cathedral|anglican church", "Ganghwa Anglican Church", "江华圣公会圣堂", "ganghwa", "heritage"),
    (r"joyang|forest outings", "Joyang Bangjik Café (Ganghwa)", "江华朝阳纺织咖啡", "ganghwa", "cafe"),
    (r"imjingak|peace bell|bridge of freedom", "Imjingak Park", "临津阁", "paju", "dmz"),
    (r"(?:3rd|third) tunnel|infiltration tunnel", "The 3rd Tunnel (DMZ)", "第三地道", "paju", "dmz"),
    (r"dora observatory", "Dora Observatory", "都罗展望台", "paju", "dmz"),
    (r"gimpo dmz", "Gimpo DMZ Tour", "金浦 DMZ 观光", "gimpo", "dmz"),
    (r"\bdmz\b", "DMZ Tour", "DMZ 非军事区", "paju", "dmz"),
    (r"heyri|paju book", "Heyri Art Valley", "Heyri 艺术村", "paju", "village"),
    (r"(?<!meta )provence", "Paju Provence Village", "坡州普罗旺斯村", "paju", "village"),
    (r"ilsan lake", "Ilsan Lake Park", "一山湖水公园", "goyang", "park"),
    (r"one mount", "One Mount", "One Mount 乐园", "goyang", "themepark"),
    (r"sangumburi|sanggumburi", "Sangumburi Crater", "山君不离", "jeju", "nature"),
    (r"yangpyeong|dumulmeori|semiwon", "Yangpyeong Dumulmeori", "杨平两水头", "yangpyeong", "nature"),
    (r"\beobi", "Eobi Ice Valley", "鱼飞溪谷冰瀑", "gapyeong", "nature"),
    (r"teseum", "Teseum Safari", "Teseum 野生动物园", "ganghwa", "themepark"),
    (r"saebyeol|friends zoo", "Saebyeol Friends Zoo", "新别动物农场", "jeju", "farm"),
    (r"guam farm", "Guam Farm (Fruit Picking)", "九岩农场（采摘）", "gimpo", "farm"),
    (r"strawberr", "Strawberry Picking", "草莓采摘", "seoul", "farm"),
    (r"choco ?pie", "Choco Pie DIY", "巧克力派 DIY", "seoul", "experience"),
    (r"glamping", "Glamping Stay", "豪华露营", "gapyeong", "experience"),
    # ---------- 江原道 ----------
    (r"seorak|soraksan|ulsanbawi|gwongeumseong", "Seoraksan National Park & Gwongeumseong Cable Car", "雪岳山国立公园·权金城缆车", "sokcho", "nature"),
    (r"naksansa", "Naksansa Temple", "洛山寺", "yangyang", "temple"),
    (r"sokcho (?:jungang|tourist fishery)|abai", "Sokcho Jungang Market & Abai Village", "束草中央市场·阿爸村", "sokcho", "market"),
    (r"balwang", "Mt Balwang Cable Car (Yongpyong)", "发旺山缆车", "pyeongchang", "ride"),
    (r"yongpyong", "Yongpyong Resort", "龙平滑雪度假村", "pyeongchang", "ski"),
    (r"alpensia", "Alpensia Resort", "阿尔卑西亚度假村", "pyeongchang", "ski"),
    (r"phoenix park|phoenix pyeongchang", "Phoenix Pyeongchang", "凤凰平昌滑雪场", "pyeongchang", "ski"),
    (r"vivaldi|sono park", "Sono Vivaldi Park", "大明维瓦尔第滑雪场", "hongcheon", "ski"),
    (r"elysian", "Elysian Gangchon", "江村伊利森滑雪场", "chuncheon", "ski"),
    (r"welli ?hilli", "Welli Hilli Park", "Welli Hilli 滑雪场", "hoengseong", "ski"),
    (r"high ?1|high ?one(?! rail)", "High1 Resort", "High1 滑雪场", "jeongseon", "ski"),
    (r"jisan", "Jisan Forest Resort", "芝山滑雪场", "icheon", "ski"),
    (r"ski (?:resort|activities|lesson)|skiing|snow activities|snow sled|snowy land", "Ski Resort (snow activities)", "滑雪场（雪地活动）", "pyeongchang", "ski"),
    (r"woljeong-?sa", "Woljeongsa Temple & Fir Forest Road", "月精寺·冷杉林路", "pyeongchang", "temple"),
    (r"needle fir|fir forest", "Woljeongsa Fir Forest Road", "月精寺冷杉林路", "pyeongchang", "nature"),
    (r"jeongdongjin|jeongdongin", "Jeongdongjin (Rail Bike & Station)", "正东津（铁路自行车）", "gangneung", "ride"),
    (r"gyeongpodae|gyeongpo", "Gyeongpodae & Gyeongpo Beach", "镜浦台·镜浦海边", "gangneung", "beach"),
    (r"anmok|coffee street", "Anmok Beach Café Street", "安木海边咖啡街", "gangneung", "cafe"),
    (r"gangneung jungang|jungang market(?=.*gangneung)", "Gangneung Jungang Market", "江陵中央市场", "gangneung", "market"),
    (r"seongyojang|seogyojang", "Seongyojang House", "船桥庄", "gangneung", "heritage"),
    (r"heo ?gyun|heonan|seolheon", "Heo Gyun & Heo Nanseolheon Memorial Park", "许筠许兰雪轩纪念公园", "gangneung", "heritage"),
    (r"ojukheon", "Ojukheon House", "乌竹轩", "gangneung", "heritage"),
    (r"jumunjin|bts bus stop", "Jumunjin (BTS Bus Stop)", "注文津（BTS 公交站）", "gangneung", "beach"),
    (r"high ?one rail|jeongseon rail|gujeolli", "Jeongseon Rail Bike", "旌善铁路自行车", "jeongseon", "ride"),
    (r"haesindang|samcheok (?:ocean )?cable", "Samcheok Ocean Cable Car", "三陟海洋缆车", "samcheok", "ride"),
    (r"sancheoneo|ice fishing", "Hwacheon Sancheoneo Ice Festival", "华川山鳟鱼冰钓节", "hwacheon", "festival"),
    (r"hongcheon ginkgo", "Hongcheon Ginkgo Forest", "洪川银杏林", "hongcheon", "nature"),
    (r"sogeumsan|mir 309", "Sogeumsan Suspension Bridge (Wonju)", "小金山出口吊桥", "wonju", "observatory"),
    (r"\by park\b|cheongnyeongpo|hanbando", "Yeongwol Y Park & Hanbando Terrain", "宁越 Y Park", "yeongwol", "park"),
    # ---------- 忠清道 ----------
    (r"dodam|mancheonha|ondal|gosu cave", "Danyang Dodamsambong & Mancheonha Skywalk", "丹阳岛潭三峰·万天下天空步道", "danyang", "nature"),
    (r"cheongpung", "Cheongpung Lake Cable Car", "清风湖缆车", "jecheon", "ride"),
    (r"oksunbong", "Oksunbong Peak Suspension Bridge", "玉筍峰出口吊桥", "jecheon", "observatory"),
    (r"woraksan", "Woraksan National Park", "月岳山国立公园", "jecheon", "nature"),
    (r"beopjusa", "Beopjusa Temple", "法住寺", "boeun", "temple"),
    (r"white dandelion|jujube", "White Dandelion Village (Boeun)", "报恩白蒲公英村", "boeun", "experience"),
    (r"gongsanseong|muryeong|gongju national museum", "Gongju Gongsanseong & Tomb of King Muryeong", "公州公山城·武宁王陵", "gongju", "heritage"),
    (r"baekje cultural land|jeongnimsa|nakhwaam|gungnamji|busosan", "Buyeo Baekje Historic Areas", "扶余百济历史遗迹区", "buyeo", "heritage"),
    (r"hwangpo sailboat|baekmagang", "Baekmagang River Hwangpo Sailboat", "白马江黄布帆船", "buyeo", "ride"),
    (r"expo science|hanbit tower", "Daejeon Expo Science Park", "大田世博科学公园", "daejeon", "park"),
    (r"sungsimdang|sung sim dang", "Sungsimdang Bakery", "圣心堂面包", "daejeon", "market"),
    (r"lee ?sung ?dang", "Lee Sung Dang Bakery", "李圣堂面包（群山）", "gunsan", "market"),
    (r"gyejoksan", "Gyejoksan Red Clay Trail", "鸡足山黄土路", "daejeon", "nature"),
    (r"jangtaesan", "Jangtaesan Recreational Forest", "长泰山休养林", "daejeon", "nature"),
    (r"yedang", "Yedang Lake Suspension Bridge", "礼唐湖出口吊桥", "yesan", "observatory"),
    (r"haemi", "Haemieupseong Fortress", "海美邑城", "seosan", "heritage"),
    (r"thalasso|taean tulip|anmyeondo", "Taean Thalassotherapy & Tulip Festival", "泰安海洋疗养·郁金香节", "taean", "experience"),
    (r"mud festival|daecheon", "Boryeong Mud Festival / Daecheon Beach", "保宁泥浆节·大川海水浴场", "boryeong", "festival"),
    (r"cheongnamdae", "Cheongnamdae", "青南台", "cheongju", "heritage"),
    (r"suanbo", "Suanbo Hot Spring", "水安堡温泉", "chungju", "experience"),
    (r"chungju lake|tangeumdae", "Chungju Lake / Tangeumdae", "忠州湖·弹琴台", "chungju", "nature"),
    (r"geumpung|brewery|makgeolli brewery", "Traditional Brewery Visit", "传统酒坊参观", "jincheon", "experience"),
    (r"onyang|hyeonchungsa|oeam", "Asan Oeam Folk Village", "牙山外岩民俗村", "asan", "village"),
    # ---------- 全罗道 ----------
    (r"jeonju hanok|hanok village(?=.*jeonju)|jeonju(?: hanok)? village", "Jeonju Hanok Village", "全州韩屋村", "jeonju", "village"),
    (r"jeondong", "Jeondong Catholic Cathedral", "殿洞天主教堂", "jeonju", "heritage"),
    (r"gyeonggijeon", "Gyeonggijeon Shrine", "庆基殿", "jeonju", "heritage"),
    (r"jeonju arboretum", "Jeonju Arboretum", "全州树木园", "jeonju", "park"),
    (r"wangyijimil", "Wangyijimil Hanok Stay (Jeonju)", "全州王的家韩屋住宿", "jeonju", "experience"),
    (r"gyeongam|railroad village", "Gunsan Gyeongam-dong Railroad Village", "群山京岩洞铁路村", "gunsan", "village"),
    (r"naejang", "Naejangsan National Park", "内藏山国立公园", "jeongeup", "nature"),
    (r"baekyang", "Baekyangsa Temple", "白羊寺", "jangseong", "temple"),
    (r"metasequoia|meta provence", "Damyang Metasequoia Road", "潭阳水杉林道", "damyang", "nature"),
    (r"juknokwon|bamboo forest(?=.*damyang)|damyang bamboo", "Damyang Juknokwon Bamboo Forest", "潭阳竹绿苑", "damyang", "nature"),
    (r"soswaewon", "Soswaewon Garden", "潇洒园", "damyang", "park"),
    (r"boseong|daehan dawon", "Boseong Green Tea Plantation", "宝城绿茶园", "boseong", "nature"),
    (r"suncheon ?(?:man|bay)|suncheonman", "Suncheon Bay Wetland Reserve", "顺天湾湿地", "suncheon", "nature"),
    (r"suncheon ?(?:bay )?(?:national )?garden", "Suncheon Bay National Garden", "顺天湾国家庭园", "suncheon", "park"),
    (r"nagan|naganeupseong", "Naganeupseong Folk Village", "乐安邑城民俗村", "suncheon", "village"),
    (r"odongdo|expo aquarium|dolsan|yeosu (?:maritime )?cable|nangman", "Yeosu Odongdo & Maritime Cable Car", "丽水梧桐岛·海上缆车", "yeosu", "nature"),
    (r"mokpo (?:marine )?cable|gatbawi|yudalsan", "Mokpo Marine Cable Car", "木浦海上缆车", "mokpo", "ride"),
    (r"jeungdo|taepyeong salt|salt (?:farm|harvest)", "Jeungdo Taepyeong Salt Farm", "曾岛太平盐田", "sinan", "experience"),
    (r"wando tower|marine healing|cheongsando", "Wando Marine Healing Centre & Seaweed Museum", "莞岛海洋治愈中心·海藻博物馆", "wando", "experience"),
    (r"ttangkkeut|daeheungsa|sweet potato bread|land.s end", "Haenam (Land's End / Daeheungsa)", "海南（地端村·大兴寺）", "haenam", "nature"),
    (r"seomjingang|sansuyu|hwaeomsa", "Gurye Seomjingang Cherry Blossom Road", "求礼蟾津江樱花路", "gurye", "festival"),
    (r"maehwa", "Gwangyang Maehwa (Plum) Village", "光阳梅花村", "gwangyang", "festival"),
    (r"1913|songjeong station", "Gwangju 1913 Songjeong Station Market", "光州 1913 松汀站市场", "gwangju", "market"),
    (r"chungjang|asia culture center|yangnim", "Gwangju Yangnim-dong / ACC", "光州杨林洞·亚洲文化殿堂", "gwangju", "district"),
    (r"gwanghallu|chunhyang", "Namwon Gwanghallu Garden", "南原广寒楼苑", "namwon", "park"),
    (r"soyang hanok|ogung", "Wanju Ogung Hanok Village (BTS)", "完州五宫韩屋村", "wanju", "village"),
    # ---------- 庆尚北道 / 大邱 ----------
    (r"bulguksa", "Bulguksa Temple", "佛国寺", "gyeongju", "temple"),
    (r"seokguram", "Seokguram Grotto", "石窟庵", "gyeongju", "temple"),
    (r"cheomseongdae", "Cheomseongdae Observatory", "瞻星台", "gyeongju", "heritage"),
    (r"daereungwon|tumuli|tomb complex|cheonmachong", "Daereungwon Tomb Complex", "大陵苑", "gyeongju", "heritage"),
    (r"donggung|wolji|anapji", "Donggung Palace & Wolji Pond", "东宫与月池（雁鸭池）", "gyeongju", "heritage"),
    (r"hwangni|hwangridan", "Hwangnidan-gil", "皇理团路", "gyeongju", "district"),
    (r"gyochon|kyochon (?:village|hanok)", "Gyochon Hanok Village", "校村韩屋村", "gyeongju", "village"),
    (r"woljeong ?gyo|woljeongyo", "Woljeonggyo Bridge", "月精桥", "gyeongju", "heritage"),
    (r"bomun", "Bomun Lake Resort", "普门湖", "gyeongju", "park"),
    (r"gyeongju national museum", "Gyeongju National Museum", "国立庆州博物馆", "gyeongju", "museum"),
    (r"gyeongju world|gyeongju tower", "Gyeongju World", "庆州世界乐园", "gyeongju", "themepark"),
    (r"yangdong", "Yangdong Folk Village", "良洞民俗村", "gyeongju", "village"),
    (r"hahoe", "Andong Hahoe Folk Village", "安东河回村", "andong", "village"),
    (r"byeongsan|dosan seowon|wolyeonggyo|woryeonggyo", "Andong Confucian Academies / Woryeonggyo", "安东书院·月映桥", "andong", "heritage"),
    (r"dongseongno|dongseong-ro", "Dongseongno (Daegu)", "东城路（大邱）", "daegu", "district"),
    (r"seomun market", "Seomun Market", "西门市场", "daegu", "market"),
    (r"83 tower|e-?world|e-word", "E-World & 83 Tower", "E-World·83塔", "daegu", "themepark"),
    (r"spa valley", "Daegu Spa Valley", "大邱 Spa Valley", "daegu", "themepark"),
    (r"kim kwang ?seok", "Kim Kwang-seok Street", "金光石街", "daegu", "district"),
    (r"daegu (?:traditional|korean traditional) culture|traditional culture center", "Daegu Korean Traditional Culture Center", "大邱传统文化体验馆", "daegu", "experience"),
    (r"palgongsan|donghwasa", "Palgongsan & Donghwasa Temple", "八公山·桐华寺", "daegu", "temple"),
    (r"saejae|open set|ecological maze", "Mungyeong Saejae Provincial Park & Drama Set", "闻庆鸟岭·电视剧拍摄地", "mungyeong", "nature"),
    (r"homigot", "Homigot Sunrise Square", "虎尾串日出广场", "pohang", "observatory"),
    (r"space ?walk|hwanho", "Hwanho Park Space Walk", "环湖公园太空漫步", "pohang", "observatory"),
    (r"guryongpo", "Guryongpo Japanese House Street", "九龙浦日式房屋街", "pohang", "district"),
    (r"jukdo market", "Jukdo Market", "竹岛市场", "pohang", "market"),
    (r"ulleung|dokdo", "Ulleungdo & Dokdo", "郁陵岛·独岛", "ulleungdo", "island"),
    (r"eunseong|apple (?:pie|farm|wine)", "Apple Farm & DIY Apple Pie", "苹果农场·苹果派 DIY", "yesan", "farm"),
    (r"cheongdo", "Cheongdo Wine Tunnel", "清道红酒隧道", "cheongdo", "experience"),
    (r"buseoksa|sosu seowon|seonbichon", "Yeongju Buseoksa Temple", "荣州浮石寺", "yeongju", "temple"),
    # ---------- 釜山 / 庆尚南道 / 蔚山 ----------
    (r"gamcheon", "Gamcheon Culture Village", "甘川洞文化村", "busan", "village"),
    (r"haedong ?yonggung|yonggungsa", "Haedong Yonggungsa Temple", "海东龙宫寺", "busan", "temple"),
    (r"sky capsule|blue ?line park|beach train|blue marine park|blueline", "Haeundae Blue Line Park (Sky Capsule & Beach Train)", "海云台蓝线公园（天空胶囊·海边列车）", "busan", "ride"),
    (r"cheongsapo|daritdol", "Cheongsapo Daritdol Skywalk", "青沙浦踏石展望台", "busan", "observatory"),
    (r"haeundae(?! blue| skywalk| beach train)|haeundae beach", "Haeundae Beach", "海云台海水浴场", "busan", "beach"),
    (r"x the sky|busan x", "BUSAN X the SKY (LCT)", "釜山 X the SKY 观景台", "busan", "observatory"),
    (r"the bay 101|bay101", "The Bay 101", "The Bay 101 海云台夜景", "busan", "district"),
    (r"dongbaek|nurimaru|apec house", "Dongbaek Island & Nurimaru APEC House", "冬柏岛·APEC世峰楼", "busan", "park"),
    (r"gwangalli|gwangan", "Gwangalli Beach & Gwangan Bridge", "广安里海滩·广安大桥", "busan", "beach"),
    (r"millac|yacht", "Busan Yacht Tour", "釜山游艇", "busan", "ride"),
    (r"songdo (?:sea |marine )?cable|air cruise", "Songdo Marine Cable Car (Busan Air Cruise)", "松岛海上缆车", "busan", "ride"),
    (r"songdo (?:yonggung )?(?:suspension|cloud|sky)walk|yonggung suspension|songdo yonggung", "Songdo Yonggung Suspension Bridge", "松岛龙宫云桥", "busan", "observatory"),
    (r"songdo beach|amnam", "Songdo Beach", "松岛海水浴场", "busan", "beach"),
    (r"taejongdae", "Taejongdae", "太宗台", "busan", "nature"),
    (r"oryukdo", "Oryukdo Skywalk", "五六岛天空步道", "busan", "observatory"),
    (r"igidae|igari|anchor observatory", "Igidae / Igari Anchor Observatory", "二妓台·锚形展望台", "busan", "observatory"),
    (r"jagalchi", "Jagalchi Fish Market", "札嘎其鱼市场", "busan", "market"),
    (r"gukje", "Gukje Market", "国际市场", "busan", "market"),
    (r"biff|nampo", "BIFF Square & Nampo-dong", "BIFF 广场·南浦洞", "busan", "district"),
    (r"bupyeong|kkangtong", "Bupyeong Kkangtong Night Market", "富平罐头夜市", "busan", "market"),
    (r"seomyeon|jeonpo", "Seomyeon & Jeonpo Café Street", "西面·田浦咖啡街", "busan", "district"),
    (r"un memorial|un cemetery", "UN Memorial Cemetery", "联合国纪念公园", "busan", "heritage"),
    (r"busan tower|yongdusan", "Busan Tower (Yongdusan Park)", "釜山塔（龙头山公园）", "busan", "observatory"),
    (r"huinnyeoul|huinyeoul", "Huinnyeoul Culture Village", "白浅滩文化村", "busan", "village"),
    (r"dongbusan|osiria", "Lotte Premium Outlet Dongbusan", "乐天名品奥特莱斯（东釜山）", "busan", "outlet"),
    (r"lotte world busan|lotte world adventure busan", "Lotte World Adventure Busan", "釜山乐天世界", "busan", "themepark"),
    (r"skyline luge", "Skyline Luge Busan", "Skyline 斜坡滑车", "busan", "ride"),
    (r"shinsegae centum|centum city|spaland", "Shinsegae Centum City & Spaland", "新世界 Centum 城·Spaland", "busan", "outlet"),
    (r"clubd|club d oasis", "CLUBD OASIS (Spa)", "CLUBD OASIS 水疗", "busan", "experience"),
    (r"busan subway|t-?money", "Busan Subway Experience", "釜山地铁体验", "busan", "experience"),
    (r"firework", "Busan Fireworks Festival", "釜山烟花节", "busan", "festival"),
    (r"jinhae|gunhangje|yeojwacheon|gyeonghwa|kyunghwa|jangbok", "Jinhae Gunhangje Cherry Blossom Festival", "镇海军港节樱花（余佐川·庆和站）", "changwon", "festival"),
    (r"windy hill|\boedo\b|haegeumgang|geoje (?:panorama )?cable", "Geoje Windy Hill & Oedo Botania", "巨济风之丘·外岛", "geoje", "island"),
    (r"mireuksan|dongpirang|hallyeosu|tongyeong cable", "Tongyeong Cable Car & Dongpirang Village", "统营缆车·东皮郎壁画村", "tongyeong", "ride"),
    (r"german village|daraengi", "Namhae German Village", "南海德国村", "namhae", "village"),
    (r"jinju fortress|chokseokru|lantern festival", "Jinju Fortress", "晋州城", "jinju", "heritage"),
    (r"choi champan|ssanggyesa|hadong (?:green )?tea", "Hadong (Green Tea & Choi Champan House)", "河东（绿茶·崔参判宅）", "hadong", "village"),
    (r"daepohang|daepohaeng", "Daepohang Fishery Market", "大浦港水产市场", "sokcho", "market"),
    (r"daewangam|ganjeolgot|taehwagang|simni", "Ulsan Daewangam & Taehwagang Garden", "蔚山大王岩·太和江国家庭园", "ulsan", "nature"),
    (r"tongdosa", "Tongdosa Temple", "通度寺", "yangsan", "temple"),
    (r"gaya theme|suro", "Gimhae Gaya Theme Park", "金海伽倻主题公园", "gimhae", "heritage"),
    (r"yeongnamnu", "Miryang Yeongnamnu", "密阳岭南楼", "miryang", "heritage"),
    # ---------- 济州 ----------
    (r"seongsan|ilchulbong|sunrise peak", "Seongsan Ilchulbong (Sunrise Peak)", "城山日出峰", "jeju", "nature"),
    (r"seopjikoji", "Seopjikoji", "涉地可支", "jeju", "nature"),
    (r"\budo\b|udobong", "Udo Island", "牛岛", "udo", "island"),
    (r"geommeolle", "Geommeolle Beach (Udo)", "黑沙滩（牛岛）", "udo", "beach"),
    (r"seobin|baeksa", "Seobin Baeksa Beach (Udo)", "西滨白沙（牛岛）", "udo", "beach"),
    (r"o.?sulloc|osulloc|innisfree", "O'sulloc Tea Museum & Innisfree House", "雪绿茶博物馆·悦诗风吟", "seogwipo", "museum"),
    (r"camellia hill", "Camellia Hill", "山茶花之丘", "seogwipo", "park"),
    (r"snoopy", "Snoopy Garden", "史努比花园", "jeju", "themepark"),
    (r"herb dongsan", "Jeju Herb Dongsan", "济州香草园", "seogwipo", "park"),
    (r"aromatherapy footbath|foot ?bath", "Aromatherapy Footbath", "香薰足浴", "seogwipo", "experience"),
    (r"dongmun", "Jeju Dongmun Market", "东门传统市场", "jeju", "market"),
    (r"olle market|maeil olle", "Seogwipo Maeil Olle Market", "西归浦每日偶来市场", "seogwipo", "market"),
    (r"yongduam|dragon head", "Yongduam (Dragon Head Rock)", "龙头岩", "jeju", "nature"),
    (r"yongyeon", "Yongyeon Suspension Bridge", "龙渊吊桥", "jeju", "nature"),
    (r"rainbow coast|dodubong|\biho\b", "Rainbow Coastal Road & Iho Tewoo Beach", "彩虹海岸路·梨湖海边", "jeju", "beach"),
    (r"aewol", "Aewol Café Street", "涯月咖啡街", "jeju", "cafe"),
    (r"hyeopjae|hallim park|hanllim park|hallim", "Hallim Park & Hyeopjae Beach", "翰林公园·挟才海水浴场", "jeju", "beach"),
    (r"jusangjeolli|jungmun|daepo jusang", "Jusangjeolli Cliff", "柱状节理带", "seogwipo", "nature"),
    (r"cheonjiyeon|cheonjeyeon", "Cheonjiyeon / Cheonjeyeon Falls", "天地渊/天帝渊瀑布", "seogwipo", "nature"),
    (r"jeongbang", "Jeongbang Waterfall", "正房瀑布", "seogwipo", "nature"),
    (r"sanbang|yongmeori", "Sanbangsan & Yongmeori Coast", "山房山·龙头海岸", "seogwipo", "nature"),
    (r"songaksan", "Songaksan", "松岳山", "seogwipo", "nature"),
    (r"hallasan|halla san|mount halla", "Hallasan National Park", "汉拿山国立公园", "jeju", "nature"),
    (r"halla sumokwon|sumokwon", "Halla Arboretum", "汉拿树木园", "jeju", "park"),
    (r"healing forest", "Seogwipo Healing Forest", "西归浦治愈森林", "seogwipo", "nature"),
    (r"bijarim", "Bijarim Forest", "榧子林", "jeju", "nature"),
    (r"saryeoni", "Saryeoni Forest Path", "思连伊林荫道", "jeju", "nature"),
    (r"keuneonggot|sanyang", "Sanyang Keuneonggot", "山阳大洞穴（Keuneonggot）", "jeju", "nature"),
    (r"secret forest", "Jeju Secret Forest", "济州秘密森林", "jeju", "nature"),
    (r"gotjawal|gottjawal|fantasy forest", "Gotjawal Forest", "Gotjawal 原始林", "jeju", "nature"),
    (r"seongeup", "Seongeup Folk Village", "城邑民俗村", "seogwipo", "village"),
    (r"jeju folk village", "Jeju Folk Village", "济州民俗村", "seogwipo", "village"),
    (r"stone park", "Jeju Stone Park", "济州石文化公园", "jeju", "park"),
    (r"donghwa village", "Jeju Donghwa Village", "济州童话村", "jeju", "village"),
    (r"arte museum", "ARTE Museum Jeju", "ARTE 光影美术馆（济州/釜山/江陵/丽水均有）", "jeju", "museum"),
    (r"bonte", "Bonte Museum", "本态博物馆", "seogwipo", "museum"),
    (r"9\.81|981 park", "9.81 Park", "9.81 公园（无动力赛车）", "jeju", "themepark"),
    (r"water world", "Jeju Water World", "济州水世界", "jeju", "themepark"),
    (r"horse ?(?:back)? ?riding", "Horse Riding", "骑马体验", "jeju", "experience"),
    (r"haenyeo", "Haenyeo (Women Divers) Show", "海女表演", "jeju", "show"),
    (r"tangerine|hallabong|mureung", "Tangerine Picking / Jam DIY", "柑橘采摘·果酱 DIY", "jeju", "farm"),
    (r"black pork street", "Jeju Black Pork Street", "黑猪肉一条街", "jeju", "district"),
    (r"canola|gasiri", "Canola Flower Fields", "油菜花田", "jeju", "festival"),
    (r"samseonghyeol", "Samseonghyeol Shrine", "三姓穴", "jeju", "heritage"),
    (r"loveland|love land", "Jeju Loveland", "济州爱情乐园", "jeju", "themepark"),
    (r"mysterious road|dokkaebi", "Mysterious Road", "神秘之路", "jeju", "nature"),
    (r"jeju university street|cherry blossom.*jeonnong|jeonnong", "Jeonnong-ro Cherry Blossom Street", "典农路樱花街", "jeju", "festival"),
    (r"pinnacle ?land", "Pinnacleland", "Pinnacleland 树木园", "seogwipo", "park"),
    (r"inart", "INART Museum", "INART 美术馆", "jeju", "museum"),
    (r"mmango|mango museum", "Mmango Museum", "Mmango 博物馆", "jeju", "museum"),
    (r"renoburg", "Renoburg Museum", "Renoburg 博物馆", "jeju", "museum"),
    (r"woljeong-?ri|woljeongri", "Woljeong-ri Beach", "月汀里海边", "jeju", "beach"),
    (r"stay folio|haus nowhere|aqua garden", "Jeju/Seoul Concept Café", "主题网红咖啡", "jeju", "cafe"),
    (r"jeju (?:shilla|lotte) duty free", "Jeju Duty-free", "济州免税店", "jeju", "shopstop"),
    (r"hueree", "Hueree Hydrangea Garden", "休爱里绣球花园", "seogwipo", "festival"),
    # ---------- 补充（按未命中亮点补） ----------
    (r"haslla", "Haslla Art World", "哈瑟拉艺术世界", "gangneung", "museum"),
    (r"boromwat", "Boromwat Flower Farm", "宝伦瓦特花园", "jeju", "park"),
    (r"samaksan", "Samaksan Lake Cable Car", "三岳山湖缆车", "chuncheon", "ride"),
    (r"gimyujeong", "Gimyujeong Rail Bike", "金裕贞铁路自行车", "chuncheon", "ride"),
    (r"sinpo", "Sinpo International Market", "新浦国际市场", "incheon", "market"),
    (r"jogang", "Jogang Observatory", "祖江展望台", "gimpo", "dmz"),
    (r"cheongok|golden bat", "Cheongok Cave", "天谷洞窟", "donghae", "nature"),
    (r"nongoldam|mukho", "Mukho Port & Nongoldam-gil", "墨湖港·论谷潭路", "donghae", "district"),
    (r"chuam|candlestick", "Chuam Candlestick Rock", "湫岩烛台岩", "donghae", "nature"),
    (r"samseonggung|hwagae", "Hadong Samseonggung & Hwagae Market", "河东三圣宫·花开市场", "hadong", "heritage"),
    (r"boriam|geumsan", "Namhae Geumsan Boriam Hermitage", "南海锦山菩提庵", "namhae", "temple"),
    (r"treasure island observatory|naengcheon", "Namhae Coast (Treasure Island Observatory)", "南海海岸（宝物岛展望台）", "namhae", "observatory"),
    (r"namildae", "Sacheon Namildae Beach", "泗川南一台海水浴场", "sacheon", "beach"),
    (r"\bonggi", "Ulsan Onggi Village", "蔚山瓮器村", "ulsan", "museum"),
    (r"euneungjeongi|euneujeongi|so-?dong caf", "Daejeon Eunhaeng-dong / Soje-dong", "大田银杏洞·苏堤洞", "daejeon", "district"),
    (r"shinsegae art", "Daejeon Shinsegae Art & Science", "大田新世界 Art & Science", "daejeon", "outlet"),
    (r"tofu (?:street|cookie)|paju tofu", "Paju Tofu Village", "坡州豆腐村", "paju", "experience"),
    (r"goto mall|express bus terminal", "Goto Mall (Express Bus Terminal)", "高速巴士客运站地下商街", "seoul", "outlet"),
    (r"la ?veni(?:ce|che)", "Gimpo La Veniche Street", "金浦拉维尼斯水岸街", "gimpo", "district"),
    (r"nongdari", "Jincheon Nongdari Bridge", "镇川农桥", "jincheon", "heritage"),
    (r"yeonmijeong", "Yeonmijeong Pavilion (Ganghwa)", "燕尾亭（江华）", "ganghwa", "heritage"),
    (r"goseokjeong?", "Goseokjeong Flower Garden (Cheorwon)", "高石亭花园（铁原）", "cheorwon", "park"),
    (r"samsung transportation", "Samsung Transportation Museum", "三星交通博物馆", "yongin", "museum"),
    (r"gyeongui line", "Gyeongui Line Forest Park", "京义线林荫道", "seoul", "park"),
    (r"nari basin|taeha|jeodong|dodong", "Ulleungdo & Dokdo", "郁陵岛·独岛", "ulleungdo", "island"),
    (r"hamsang park|battleship", "Gimpo Hamsang Park", "金浦舰上公园", "gimpo", "park"),
    (r"gwangmyeong cave", "Gwangmyeong Cave", "光明洞窟", "gwangmyeong", "nature"),
    (r"seaweed museum", "Seaweed Museum", "海藻博物馆", "seoul", "museum"),
    (r"premium outlet", "Premium Outlet", "名品奥特莱斯", "seoul", "outlet"),
    (r"abalone harvesting", "Abalone Harvesting Experience", "捕鲍鱼体验", "jeju", "experience"),
    (r"hydrangea", "Hydrangea Viewing", "赏绣球花", "jeju", "festival"),
    # ---------- 季节通用 ----------
    (r"cherry blossom|sakura", "Cherry Blossom Viewing", "赏樱", "seoul", "festival"),
    (r"maple|fall foliage|autumn leaves|autumn foliage", "Autumn Foliage", "赏枫", "seoul", "festival"),
    (r"ginkgo", "Ginkgo Trees", "银杏", "seoul", "festival"),
    (r"tulip", "Tulip Festival", "郁金香节", "taean", "festival"),
    (r"pink muhly", "Pink Muhly Grass", "粉黛乱子草", "jeju", "festival"),
    (r"ktx|korea train express|high-speed (?:train|rail)|bullet train", "KTX High-speed Train", "KTX 高铁", "seoul", "ride"),
]

# 泛化条目：城市以当天行程城市为准（体验/购物站/季节类在多地都有）
GENERIC = {"Hanbok Dress-up Experience", "Kimchi-making Experience", "Gochujang-making Experience", "Tteokbokki Cooking Class", "Jjimjilbang (Korean Sauna)",
           "Duty-free Shop", "Ginseng Shop", "Healthy Liver Showroom", "Cosmetics Shop", "Amethyst Showroom", "Scalp Care Clinic", "Korean Chuna Therapy",
           "Lotte Mart", "K-pop Spots", "BTS Spots", "Strawberry Picking", "Choco Pie DIY", "Glamping Stay", "Guam Farm (Fruit Picking)", "Teseum Safari",
           "Ski Resort (snow activities)", "Horse Riding", "Aromatherapy Footbath", "Jeju/Seoul Concept Café", "Traditional Brewery Visit", "Apple Farm & DIY Apple Pie",
           "Premium Outlet", "Seaweed Museum", "Abalone Harvesting Experience", "Hydrangea Viewing", "NANTA Show", "Taekwondo Show", "ARTE Museum Jeju",
           "Alpaca World", "Mmango Museum", "INART Museum", "Renoburg Museum", "Spoon Mapping Café", "Lotte World Adventure",
           "Cherry Blossom Viewing", "Autumn Foliage", "Ginkgo Trees", "Tulip Festival", "Pink Muhly Grass", "KTX High-speed Train", "DMZ Tour", "Canola Flower Fields"}

_COMPILED = [(re.compile(p, re.I), en, cn, ck, cat) for p, en, cn, ck, cat in G]

# 同一短语只匹配最先命中的规则；城市级关键词（"Seoul" 等）不算景点
SKIP_HINTS = re.compile(r"^(seoul|busan|jeju(?: island)?|incheon|gyeonggi.*|gangwon.*|daegu|ulsan|pohang|gyeongju|mungyeong|jincheon|singapore|note.*|notes?:?|accommodation.*|highlights|delicacies|specialties|meal plan|\d+n.*)$", re.I)

def match_all(text):
    """在一段文字里找所有词典命中的景点，按出现位置排序，去重。返回 [(en, cn, city_key, cat)]。"""
    if not text:
        return []
    hits = []
    seen = set()
    for rx, en, cn, ck, cat in _COMPILED:
        m = rx.search(text)
        if m and en not in seen:
            seen.add(en)
            hits.append((m.start(), en, cn, ck, cat))
    # 去掉被更具体条目覆盖的泛称
    names = {h[1] for h in hits}
    generic = {"Cherry Blossom Viewing": ["Jinhae Gunhangje Cherry Blossom Festival", "Yeouido Yunjung-ro Cherry Blossom Street", "Gurye Seomjingang Cherry Blossom Road", "Jeonnong-ro Cherry Blossom Street"],
               "Ski Resort (snow activities)": ["Yongpyong Resort", "Alpensia Resort", "Phoenix Pyeongchang", "Sono Vivaldi Park", "Elysian Gangchon", "Welli Hilli Park", "High1 Resort", "Jisan Forest Resort"],
               "DMZ Tour": ["The 3rd Tunnel (DMZ)", "Dora Observatory", "Imjingak Park", "Gimpo DMZ Tour", "Aegibong Peace Ecopark", "Ganghwa Peace Observatory"],
               "Woljeongsa Fir Forest Road": ["Woljeongsa Temple & Fir Forest Road"],
               "Strawberry Picking": ["Guam Farm (Fruit Picking)"],
               "Haeundae Beach": ["Haeundae Blue Line Park (Sky Capsule & Beach Train)", "BUSAN X the SKY (LCT)", "The Bay 101"],
               "Premium Outlet": ["Hyundai Premium Outlet Gimpo", "Hyundai Premium Outlet Songdo", "Lotte Premium Outlet Dongbusan"],
               "Hydrangea Viewing": ["Hueree Hydrangea Garden"]}
    drop = {g for g, specs in generic.items() if g in names and any(s in names for s in specs)}
    hits = [h for h in hits if h[1] not in drop]
    hits.sort()
    return [h[1:] for h in hits]

def match_one(phrase):
    r = match_all(phrase)
    return r[0] if r else None

BY_EN = {en: (en, cn, ck, cat) for _, en, cn, ck, cat in G}
